# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.
# Site Settings
locale: "de-DE"
title: "Jonas Freizeit Blog"
title_separator: "-"
name: &name "Jonas Geiselhart"
description: &description "Contains in at the moment only one Entry for the ML4Sci Seminar of the University of Stuttgart"
url: "https://https://jonetz.github.io/"  # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: ""  # the subpath of your site, e.g. "/blog"
repository: "academicpages/academicpages.github.io"
teaser: ""  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs: false  # true, false (default)
words_per_minute: 160
future: true
read_more: "disabled"  # if enabled, adds "Read more" links to excerpts
talkmap_link: false  # change to true to add a link to talkmap on the talks page
comments:
  provider: null  # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname: null
  discourse:
    server: null  # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid: null
    num_posts: null  # 5 (default)
    colorscheme: null  # "light" (default), "dark"
staticman:
  allowedFields: ['name', 'email', 'url', 'message']
  branch: "gh-pages"  # "master", "gh-pages"
  commitMessage: "New comment."
  filename: "comment-{@timestamp}"
  format: "yml"
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email: "md5"
  generatedFields:
    date:
      type: "date"
      options:
        format: "iso8601"  # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path: ""  # blank (default) uses feed.xml

# SEO Related
google_site_verification: null
bing_site_verification: null
alexa_site_verification: null

# Social Sharing
og_image: null  # Open Graph/Twitter default site image

# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
# social:
#   type: null  # Person or Organization (defaults to Person)
#   name: null  # If the user or organization name differs from the site's name
#   links:  # An array of links to social media profiles

# Analytics
# analytics:
#   provider: "google-universal"  # false (default), "google", "google-universal", "custom"
#   google:
#     tracking_id: null

# Site Author
author:
  name: "Jonas Geiselhart"
  avatar: "profile.png"
  bio: "Currently, I am studying for my Masters in Artificial Intelligence and Data Science at the University of Stuttgart"
  location: "Weil der Stadt"
  employer: null
  pubmed: null
  googlescholar: null
  email: null
  researchgate: null  # example: "https://www.researchgate.net/profile/yourprofile"
  uri: null
  bitbucket: null
  codepen: null
  dribbble: null
  flickr: null
  facebook: null
  foursquare: null
  github: "Jonetz"
  google_plus: null
  keybase: null
  instagram: null
  impactstory: null  # "https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm: null
  linkedin: null
  orcid: null
  pinterest: null
  soundcloud: null
  stackoverflow: null  # http://stackoverflow.com/users/123456/username
  steam: null
  tumblr: null
  twitter: null
  vine: null
  weibo: null
  xing: null
  youtube: null
  wikipedia: null

# Reading Files
include:
  - ".htaccess"
  - "_pages"
  - "files"
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - ".asset-cache"
  - ".bundle"
  - ".jekyll-assets-cache"
  - ".sass-cache"
  - "CHANGELOG"
  - "Capfile"
  - "Gemfile"
  - "Gruntfile.js"
  - "LICENSE"
  - "README"
  - "Rakefile"
  - "assets/js/_main.js"
  - "assets/js/plugins"
  - "assets/js/vendor"
  - "config"
  - "gulpfile.js"
  - "log"
  - "node_modules"
  - "package.json"
  - "tmp"
  - "vendor"
keep_files:
  - ".git"
  - ".svn"
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Remaining configuration...
